return {
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=false,
      NONOEPIC=false,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1378549454"]={
    configuration_options={
      ["MemSpikeFix:"]=false,
      MemSpikeFixmaster_override=true,
      ["MemSpikeFixworkshop-1138490311"]="default",
      ["MemSpikeFixworkshop-1185229307"]="default",
      ["MemSpikeFixworkshop-1207269058"]="default",
      ["MemSpikeFixworkshop-1221281706"]="default",
      ["MemSpikeFixworkshop-1365141672"]="default",
      ["MemSpikeFixworkshop-1430350339"]="default",
      ["MemSpikeFixworkshop-1505270912"]="default",
      ["MemSpikeFixworkshop-1530801499"]="default",
      ["MemSpikeFixworkshop-1608191708"]="default",
      ["MemSpikeFixworkshop-1757943227"]="default",
      ["MemSpikeFixworkshop-1944472866"]="default",
      ["MemSpikeFixworkshop-2323630362"]="default",
      ["MemSpikeFixworkshop-2598087493"]="default",
      ["MemSpikeFixworkshop-2831613121"]="default",
      ["MemSpikeFixworkshop-2928652892"]="default",
      ["MemSpikeFixworkshop-345692228"]="default",
      ["MemSpikeFixworkshop-347079953"]="default",
      ["MemSpikeFixworkshop-351325790"]="default",
      ["MemSpikeFixworkshop-362175979"]="default",
      ["MemSpikeFixworkshop-375850593"]="default",
      ["MemSpikeFixworkshop-375859599"]="default",
      ["MemSpikeFixworkshop-376333686"]="default",
      ["MemSpikeFixworkshop-378160973"]="default",
      ["MemSpikeFixworkshop-458587300"]="default",
      ["MemSpikeFixworkshop-463292274"]="default",
      ["MemSpikeFixworkshop-501385076"]="default",
      ["MemSpikeFixworkshop-569043634"]="default",
      ["MemSpikeFixworkshop-623749604"]="default",
      ["MemSpikeFixworkshop-661253977"]="default",
      ["MemSpikeFixworkshop-666155465"]="default",
      ["MemSpikeFixworkshop-694531911"]="default",
      ["MemSpikeFixworkshop-727774324"]="default",
      ["MemSpikeFixworkshop-758532836"]="default",
      ["MemSpikeFixworkshop-780009141"]="default",
      ["MemSpikeFixworkshop-782961570"]="default",
      ["MemSpikeFixworkshop-786556008"]="default",
      ["MemSpikeFixworkshop-812723897"]="default",
      ["MemSpikeFixworkshop-831523966"]="default",
      ["MemSpikeFixworkshop-856487758"]="default",
      craftinghighlight=false 
    },
    enabled=true 
  },
  ["workshop-2477889104"]={
    configuration_options={
      BADGE_BG_BRIGHTNESS=60,
      BADGE_BG_OPACITY=100,
      COLOR_DOMESTICATION_DEFAULT="WHITE",
      COLOR_DOMESTICATION_ORNERY="ORANGE",
      COLOR_DOMESTICATION_PUDGY="PURPLE",
      COLOR_DOMESTICATION_RIDER="BLUE",
      COLOR_OBEDIENCE="RED",
      COLOR_TIMER="GREEN",
      ClientConfig=false,
      EnableSounds=false,
      GapModifier=0,
      HEALTH_BADGE_CLEAR_BG=false,
      HungerThreshold=10,
      OffsetX=0,
      OffsetXFine=0,
      OffsetXMult=1,
      OffsetY=0,
      OffsetYFine=0,
      OffsetYMult=1,
      SEPARATOR_BADGE_COLORS=1,
      SEPARATOR_BADGE_SETTINGS=1,
      SEPARATOR_GENERAL=1,
      SEPARATOR_POSITIONING_X=1,
      SEPARATOR_POSITIONING_Y=1,
      Scale=1,
      ShowByDefault=true,
      Theme="TheForge",
      ToggleKey="KEY_T" 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="enabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=3 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=45 },
    enabled=true 
  },
  ["workshop-856487758"]={ configuration_options={  }, enabled=true } 
}